--CREATOR TABEL

DROP TABLE IF EXISTS PCJ

CREATE TABLE PCJ
(
NPCJ INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
IMIE VARCHAR(20) COMMENT 'IMIE PACJENTA',
NAZW VARCHAR(40) COMMENT 'NAZWISKO PACJENTA',
MIEJ VARCHAR(40) COMMENT 'MIEJSCOWOSC',
ULIC VARCHAR(40) COMMENT 'ULICA',
NUMT INT(12) COMMENT 'NUMER TELEFONU PACJENTA',
DTWO DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
DAKT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
AKTW VARCHAR(1) NOT NULL DEFAULT 'T'
)

CREATE TABLE LEK
(
NLEK INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
IMIE VARCHAR(20) COMMENT 'IMIE LEKARZA',
NAZW VARCHAR(40) COMMENT 'NAZWISKO LEKARZA',
DTWO DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
DAKT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
AKTW VARCHAR(1) NOT NULL DEFAULT 'T'
)

CREATE TABLE PRZ
(
NPRZ INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
MIEJ VARCHAR(40),
ADRS VARCHAR(40),
NUMT INT(12),
PONO INT(4) COMMENT 'GODZINA OTWARCIA W MINUTACH OD POLNOCY',
POND INT(4) COMMENT 'GODZINA ZAMKNIECIA W MINUTACH OD POLNOCY',
WTOO INT(4),
WTOD INT(4),
SROO INT(4),
SROD INT(4),
CZWO INT(4),
CZWD INT(4),
PIOO INT(4),
PIOD INT(4),
SOBO INT(4),
SOBD INT(4),
NIEO INT(4),
NIED INT(4),
DTWO DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
DAKT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
AKTW VARCHAR(1) NOT NULL DEFAULT 'T'
)

CREATE TABLE GRF
(
NGRF INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
NPJC INT NOT NULL FOREIGN KEY PJC(NPJC),
NLEK INT NOT NULL FOREIGN KEY LEK.NLEK,
NPRZ INT NOT NULL FOREIGN KEY PRZ.NPRZ,
TERM DATETIME NOT NULL COMMENT 'DATA WIZYTY'
DTWO DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
DAKT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
AKTW VARCHAR(1) NOT NULL DEFAULT 'T'
)
